server:
  port: 8091

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: QWEasd123456!
    url: jdbc:mysql://127.0.0.1/kafka-template?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    hikari:
      connection-timeout: 600
      max-lifetime: 550

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update


  kafka:
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.qiaose.entity.*
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


    bootstrap-servers: 192.168.249.128:9092


mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qiaose.entity.*
